import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { hreflangAlternatesForPage } from './lib/hreflang-config.mjs';
import {
  SITE_URL,
  absoluteSitemapUrl,
  maxLastmod,
  shouldIncludeInSitemap,
  sitemapLastmodForPage,
} from './lib/sitemap-routes.mjs';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const manifestPath = path.join(rootDir, 'content/manifest.json');

const XSL_PI = `<?xml-stylesheet type="text/xsl" href="${SITE_URL}/main-sitemap.xsl"?>`;

function escapeXml(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function normalizeHref(href) {
  if (!href) return href;
  if (href.startsWith('http://') || href.startsWith('https://')) return href;
  const route = href.startsWith('/') ? href : `/${href}`;
  return absoluteSitemapUrl(route);
}

function buildHreflangLinks(page) {
  const alternates = hreflangAlternatesForPage(page);
  if (!alternates.length) return '';

  return alternates
    .map((alt) => {
      const href = normalizeHref(alt.href);
      return `\t\t<xhtml:link rel="alternate" hreflang="${escapeXml(alt.hreflang)}" href="${escapeXml(href)}" />`;
    })
    .join('\n');
}

function buildUrlEntry(page, generatedAt) {
  const loc = absoluteSitemapUrl(page.route);
  const lastmod = sitemapLastmodForPage(page, generatedAt);
  const hreflang = buildHreflangLinks(page);

  const lines = [`\t<url>`, `\t\t<loc>${escapeXml(loc)}</loc>`];
  if (hreflang) lines.push(hreflang);
  lines.push(`\t\t<lastmod>${lastmod}</lastmod>`, `\t</url>`);
  return { xml: lines.join('\n'), lastmod };
}

function buildUrlset(entries) {
  const body = entries.map((entry) => entry.xml).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>${XSL_PI}
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${body}
</urlset>
<!-- Generated by scripts/generate-sitemap.mjs -->
`;
}

function buildSitemapIndex({ postLastmod, pageLastmod }) {
  return `<?xml version="1.0" encoding="UTF-8"?>${XSL_PI}
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
\t<sitemap>
\t\t<loc>${SITE_URL}/post-sitemap.xml</loc>
\t\t<lastmod>${postLastmod}</lastmod>
\t</sitemap>
\t<sitemap>
\t\t<loc>${SITE_URL}/page-sitemap.xml</loc>
\t\t<lastmod>${pageLastmod}</lastmod>
\t</sitemap>
</sitemapindex>
<!-- Generated by scripts/generate-sitemap.mjs -->
`;
}

async function main() {
  const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
  const generatedAt = manifest.generatedAt;
  const included = manifest.pages.filter(shouldIncludeInSitemap).sort((a, b) => a.route.localeCompare(b.route));

  const postEntries = [];
  const pageEntries = [];

  for (const page of included) {
    const entry = buildUrlEntry(page, generatedAt);
    if (page.type === 'post') {
      postEntries.push(entry);
    } else {
      pageEntries.push(entry);
    }
  }

  const postSitemap = buildUrlset(postEntries);
  const pageSitemap = buildUrlset(pageEntries);
  const postLastmod = maxLastmod(postEntries, generatedAt);
  const pageLastmod = maxLastmod(pageEntries, generatedAt);
  const indexXml = buildSitemapIndex({ postLastmod, pageLastmod });

  const outputs = [
    ['post-sitemap.xml', postSitemap],
    ['page-sitemap.xml', pageSitemap],
    ['sitemap_index.xml', indexXml],
    ['sitemap.xml', indexXml],
  ];

  for (const [filename, xml] of outputs) {
    await fs.writeFile(path.join(rootDir, filename), xml, 'utf8');
  }

  console.log(
    `Generated sitemaps from manifest: ${postEntries.length} posts, ${pageEntries.length} pages -> post-sitemap.xml, page-sitemap.xml, sitemap_index.xml`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
