import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  SITE_URL,
  absoluteSitemapUrl,
  shouldIncludeInSitemap,
} from './lib/sitemap-routes.mjs';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const manifestPath = path.join(rootDir, 'content/manifest.json');

const SITEMAP_FILES = ['post-sitemap.xml', 'page-sitemap.xml', 'sitemap_index.xml', 'sitemap.xml'];

const STAGES = [
  { label: 'root', dir: rootDir },
  { label: 'public', dir: path.join(rootDir, 'apps/web/public') },
  { label: 'out', dir: path.join(rootDir, 'apps/web/out') },
];

function extractLocUrls(xml) {
  const urls = new Set();
  for (const match of xml.matchAll(/<loc>([^<]+)<\/loc>/g)) {
    urls.add(match[1]);
  }
  return urls;
}

function verifyIndexStructure(xml, label, violations) {
  const locs = [...extractLocUrls(xml)];

  if (locs.length !== 2) {
    violations.push(`[${label}] sitemap index must list exactly 2 child sitemaps, found ${locs.length}`);
  }

  const expected = [`${SITE_URL}/post-sitemap.xml`, `${SITE_URL}/page-sitemap.xml`];
  for (const loc of expected) {
    if (!locs.includes(loc)) {
      violations.push(`[${label}] sitemap index missing ${loc}`);
    }
  }

  for (const loc of locs) {
    if (loc.includes('/category-') || loc.includes('/post_tag-')) {
      violations.push(`[${label}] sitemap index must not reference taxonomy sitemap ${loc}`);
    }
  }

  if (!xml.includes('<lastmod>')) {
    violations.push(`[${label}] sitemap index missing lastmod entries`);
  }
}

function verifyUrlset(xml, label, violations) {
  const locs = [...extractLocUrls(xml)];

  if (locs.length === 0) {
    violations.push(`[${label}] urlset has no loc entries`);
  }

  for (const loc of locs) {
    if (!loc.startsWith(`${SITE_URL}/`)) {
      violations.push(`[${label}] loc must start with ${SITE_URL}/ — got ${loc}`);
    }

    if (/\/category\//.test(loc) || /\/tag\//.test(loc) || /\/team\//.test(loc)) {
      violations.push(`[${label}] excluded route in sitemap: ${loc}`);
    }
  }

  const locCount = (xml.match(/<loc>/g) ?? []).length;
  const lastmodCount = (xml.match(/<lastmod>/g) ?? []).length;
  if (locCount !== lastmodCount) {
    violations.push(
      `[${label}] every url must have lastmod (${locCount} loc, ${lastmodCount} lastmod)`,
    );
  }

  if (!xml.includes('Generated by scripts/generate-sitemap.mjs')) {
    violations.push(`[${label}] missing generator marker comment`);
  }
}

async function main() {
  const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
  const expectedPages = manifest.pages.filter(shouldIncludeInSitemap);
  const expectedUrls = new Set(expectedPages.map((page) => absoluteSitemapUrl(page.route)));

  const violations = [];

  for (const stage of STAGES) {
    const combinedUrls = new Set();

    for (const filename of ['post-sitemap.xml', 'page-sitemap.xml']) {
      const filePath = path.join(stage.dir, filename);
      let xml;
      try {
        xml = await fs.readFile(filePath, 'utf8');
      } catch {
        violations.push(`[${stage.label}] missing ${filename}`);
        continue;
      }

      verifyUrlset(xml, `${stage.label}/${filename}`, violations);
      for (const url of extractLocUrls(xml)) {
        combinedUrls.add(url);
      }
    }

    for (const filename of ['sitemap_index.xml', 'sitemap.xml']) {
      const filePath = path.join(stage.dir, filename);
      let xml;
      try {
        xml = await fs.readFile(filePath, 'utf8');
      } catch {
        violations.push(`[${stage.label}] missing ${filename}`);
        continue;
      }

      verifyIndexStructure(xml, `${stage.label}/${filename}`, violations);
    }

    for (const url of expectedUrls) {
      if (!combinedUrls.has(url)) {
        violations.push(`[${stage.label}] manifest route missing from sitemap: ${url}`);
      }
    }

    for (const url of combinedUrls) {
      if (!expectedUrls.has(url)) {
        violations.push(`[${stage.label}] unexpected sitemap URL (not in manifest): ${url}`);
      }
    }
  }

  if (violations.length) {
    console.error('verify-sitemap failed:');
    violations.slice(0, 40).forEach((line) => console.error(`  - ${line}`));
    if (violations.length > 40) {
      console.error(`  - …and ${violations.length - 40} more`);
    }
    process.exitCode = 1;
    return;
  }

  console.log(
    `verify-sitemap: OK (${expectedPages.length} manifest routes across ${STAGES.length} stages, ${SITEMAP_FILES.length} files each)`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
